// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpaXCDivIrEIyfX9rewKRtUK_f5Bv6Ilw',
    appId: '1:943908511382:web:b367d2d5f28cf010b2acb7',
    messagingSenderId: '943908511382',
    projectId: 'focusflow-acd29',
    authDomain: 'focusflow-acd29.firebaseapp.com',
    storageBucket: 'focusflow-acd29.firebasestorage.app',
    measurementId: 'G-T47PHQSBKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZqcXbU61BrC0Ks2x-AYjFgiAIjAFMSM',
    appId: '1:943908511382:android:778f97b0edb6b7b9b2acb7',
    messagingSenderId: '943908511382',
    projectId: 'focusflow-acd29',
    storageBucket: 'focusflow-acd29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3WHEbzQ8hCqU3Xezl7GPck4sxAhhQ6qY',
    appId: '1:943908511382:ios:97bccd12abac8ce0b2acb7',
    messagingSenderId: '943908511382',
    projectId: 'focusflow-acd29',
    storageBucket: 'focusflow-acd29.firebasestorage.app',
    iosBundleId: 'com.example.focusFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3WHEbzQ8hCqU3Xezl7GPck4sxAhhQ6qY',
    appId: '1:943908511382:ios:97bccd12abac8ce0b2acb7',
    messagingSenderId: '943908511382',
    projectId: 'focusflow-acd29',
    storageBucket: 'focusflow-acd29.firebasestorage.app',
    iosBundleId: 'com.example.focusFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpaXCDivIrEIyfX9rewKRtUK_f5Bv6Ilw',
    appId: '1:943908511382:web:b60134a1a6ce55e3b2acb7',
    messagingSenderId: '943908511382',
    projectId: 'focusflow-acd29',
    authDomain: 'focusflow-acd29.firebaseapp.com',
    storageBucket: 'focusflow-acd29.firebasestorage.app',
    measurementId: 'G-YG1EY5VGPW',
  );

}